const questions = [
  { q: "भारताची राजधानी कोणती आहे? / What is the capital of India?", options: ["दिल्ली / Delhi", "मुंबई / Mumbai", "कोलकाता / Kolkata", "चेन्नई / Chennai"], answer: "A" },
  { q: "पृथ्वी सूर्याभोवती किती दिवसात फेरी मारते? / Earth revolves around the Sun in how many days?", options: ["365", "180", "90", "400"], answer: "A" },
  { q: "भारतातील सर्वात मोठे राज्य कोणते? / Largest state in India by area?", options: ["महाराष्ट्र / Maharashtra", "उत्तर प्रदेश / Uttar Pradesh", "राजस्थान / Rajasthan", "मध्यप्रदेश / Madhya Pradesh"], answer: "C" },
  { q: "संगणकाचा शोध कोणी लावला? / Who invented the computer?", options: ["चार्ल्स बॅबेज / Charles Babbage", "आयझॅक न्यूटन / Newton", "टॉमस एडिसन / Edison", "गॅलिलिओ / Galileo"], answer: "A" },
  { q: "भारताचा राष्ट्रीय प्राणी कोणता? / National animal of India?", options: ["सिंह / Lion", "बिबट्या / Leopard", "वाघ / Tiger", "हत्ती / Elephant"], answer: "C" },
  { q: "पाण्याचा रासायनिक सूत्र काय आहे? / Chemical formula of water?", options: ["H2O", "CO2", "O2", "NaCl"], answer: "A" },
  { q: "भारतातील पहिला पंतप्रधान कोण? / First Prime Minister of India?", options: ["गांधीजी / Gandhi", "नेहरू / Nehru", "पटेल / Patel", "आंबेडकर / Ambedkar"], answer: "B" },
  { q: "स्वातंत्र्य दिवस कधी साजरा होतो? / Independence Day of India?", options: ["15 ऑगस्ट / August 15", "26 जानेवारी / January 26", "2 ऑक्टोबर / October 2", "25 डिसेंबर / December 25"], answer: "A" },
  { q: "संगणकात वापरला जाणारा मुख्य मेमरी प्रकार? / Main memory in computers?", options: ["RAM", "ROM", "CD", "USB"], answer: "A" },
  { q: "भारताचे चलन काय आहे? / What is the currency of India?", options: ["डॉलर / Dollar", "रुपया / Rupee", "येन / Yen", "पाउंड / Pound"], answer: "B" },
  { q: "कंपासमध्ये दिशा दाखवणारा भाग कोणता? / Which part shows direction in compass?", options: ["सुई / Needle", "काच / Glass", "डायोड / Diode", "लोहचुंबक / Magnet"], answer: "A" },
  { q: "एक डझनात किती वस्तू असतात? / How many items in one dozen?", options: ["10", "12", "20", "6"], answer: "B" },
  { q: "भारताचा राष्ट्रध्वज किती रंगांचा आहे? / How many colors in Indian flag?", options: ["2", "3", "4", "5"], answer: "B" },
  { q: "सौरमालेतील सर्वात मोठा ग्रह कोणता? / Largest planet in solar system?", options: ["पृथ्वी / Earth", "मंगळ / Mars", "शनी / Saturn", "गुरू / Jupiter"], answer: "D" },
  { q: "E-mail म्हणजे काय? / What is E-mail?", options: ["Electronic mail", "Energy mail", "Earth mail", "Easy mail"], answer: "A" },
  { q: "भारताचा शेजारी देश कोणता नाही? / Which is NOT India's neighbor?", options: ["नेपाळ / Nepal", "भूतान / Bhutan", "ब्राझील / Brazil", "श्रीलंका / Sri Lanka"], answer: "C" },
  { q: "मानवाचे हृदय एका मिनिटात किती वेळा ठोके देते? / Avg heartbeats per min?", options: ["60", "72", "90", "100"], answer: "B" },
  { q: "संगणकाला 'brain' कोण म्हणतात? / Brain of the computer?", options: ["मॉनिटर / Monitor", "CPU", "कीबोर्ड / Keyboard", "माऊस / Mouse"], answer: "B" },
  { q: "भारताचा राष्ट्रीय खेळ कोणता? / National game of India?", options: ["क्रिकेट / Cricket", "फुटबॉल / Football", "हॉकी / Hockey", "कबड्डी / Kabaddi"], answer: "C" },
  { q: "जगातील सर्वात उंच पर्वत कोणता? / Tallest mountain in the world?", options: ["सह्याद्री / Sahyadri", "एव्हरेस्ट / Everest", "हिमालय / Himalaya", "आल्प्स / Alps"], answer: "B" }
];
